aboutme/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf import settings
from django.conf.urls.static import static

from django.views.generic import RedirectView

urlpatterns = [
    # path('', RedirectView.as_view(url='aboutme/')),
    path('admin/', admin.site.urls),
    path('', include('mywebsite.urls')),
] #+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mywebsite/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static


from . import views

app_name = "mywebsite"
urlpatterns = [
    path('', views.index),
    path('media/files/cv', views.Resume.as_view(), name="Resume"),
    path('project/<int:pk>/', views.ProjectView.as_view(), name="ProjectView"),
] #+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mywebsite/models.py
import os
import uuid

from django.db import models
from django.conf import settings
from django.core.files.storage import FileSystemStorage
from grifo_utils.paths.validators import FileValidator
from grifo_utils.db.abstract_models import BaseAbstractModel
from colorfield.fields import ColorField
from grifo_utils.os.system import _delete_file
import boto3
from django.conf import Settings, settings

BUCKET_NAME = settings.AWS_STORAGE_BUCKET_NAME
s3 = boto3.client(  's3',
                    aws_access_key_id=settings.AWS_ACCESS_KEY_ID,
                    aws_secret_access_key=settings.AWS_SECRET_ACCESS_KEY,
                    region_name = 'eu-west-2')


def get_extension(instance, filename):
    _, extension = os.path.splitext(filename)
    return extension

def get_upload_path_pp(instance, filename):
        _, extension = os.path.splitext(filename)
        return f"files_uploaded/{uuid.uuid4()}{extension}"

def get_upload_path_file(instance, filename):
        name, extension = os.path.splitext(filename)
        return f"files/{name}{extension}"


# Create your models here.

class Tag(models.Model):
    name = models.CharField(max_length=100)

    class Meta:
        db_table = "db_Tag"
        verbose_name = "Tag"
        verbose_name_plural = "Tags"

    def __str__(self): # pragma: no cover
        return str(self.name)


class Project(BaseAbstractModel):

    COLOR_CHOICES = [
        ("#19C801", "green"),
        ("#FCF900", "yellow"),
        ("#F50B0B", "red"),
        ("#0B2BF5", "blue"),
        ("#129CFF", "baby blue"),
        ("#E800D6", "purple")
    ]

    title = models.CharField(max_length=120)
    description = models.CharField(max_length=1000)
    tags = models.ManyToManyField(Tag, related_name='list_tags', editable=True)
    image = models.OneToOneField("ContentMultimediaFile", on_delete=models.SET_NULL, null=True, blank=True)
    color = ColorField(default='#129CFF')

    class Meta:
        db_table = "db_Project"
        verbose_name = "Project"
        verbose_name_plural = "Projects"

    def __str__(self): # pragma: no cover
        return str(self.title)


class Paragraph(models.Model):
    id_name = models.CharField(max_length=120, unique=True)
    body = models.TextField(max_length=3000)
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    content = models.OneToOneField("ContentMultimediaFile", on_delete=models.SET_NULL, null=True, blank=True)
    


    class Meta:
        db_table = "db_Paragraph"
        verbose_name = "Paragraph"
        verbose_name_plural = "Paragraphs"

    def __str__(self): # pragma: no cover
        return str(self.id_name)

class ContentMultimediaFileType(models.Model):
    IMAGE = 1
    AUDIO = 2
    VIDEO = 3

    content_multimedia_file_type = models.CharField("Content Multimedia File Type", max_length=100)

    class Meta:
        db_table = "db_ContentMultimediaFileType"
        verbose_name = "Content Multimedia File Type"
        verbose_name_plural = "Content Multimedia File Types"

    def __str__(self): # pragma: no cover
        return str(self.content_multimedia_file_type)

class CV(BaseAbstractModel):
    file_upload = models.FileField(#torage=FileSystemStorage(location=settings.MEDIA_FOLDER),
                                    upload_to=get_upload_path_file)

    class Meta:
        db_table = "db_cv"
        verbose_name = "cv"
        verbose_name_plural = "cv"

    def save(self, *args, **kwargs):
        #_delete_file(settings.MEDIA_FOLDER+"/files/brunogrifo.pdf")
        s3.delete_object(Bucket=BUCKET_NAME, Key='media/files/brunogrifo.pdf')
        super(CV, self).save(*args, **kwargs)

class ContentMultimediaFile(BaseAbstractModel):
    file_upload = models.FileField(
        #storage=FileSystemStorage(location=settings.MEDIA_FOLDER),
        upload_to=get_upload_path_pp,
        validators=[
            FileValidator(
                max_size=1024 * 1024 * 20,
                content_types=("video/mp4", "video/mpeg", "video/quicktime", "video/webm", "video/x-ms-wmv", "image/jpeg", "image/jpg", "image/png", "image/gif"),
            )
        ],
        default="default/", max_length=500)
    file_name =  models.CharField(max_length=500, null=True, blank=True)
    content_multimedia_file_type = models.ForeignKey(ContentMultimediaFileType, on_delete=models.PROTECT)

    class Meta:
        db_table = "db_ContentMultimediaFile"
        verbose_name = "Conteúdo Multimédia"
        verbose_name_plural = "Conteúdos Multimédia"

    def save(self, *args, **kwargs):
        if self.pk is None:
            if get_extension(self, self.file_upload.name) in [".mp4", ".webm"]:
                content_type = ContentMultimediaFileType.objects.get(pk=ContentMultimediaFileType.VIDEO)
                self.content_multimedia_file_type = content_type
            if get_extension(self, self.file_upload.name) in [".jpeg", ".png", ".gif", ".jpg"]:
                content_type = ContentMultimediaFileType.objects.get(pk=ContentMultimediaFileType.IMAGE)
                self.content_multimedia_file_type = content_type
            if get_extension(self, self.file_upload.name) in [".wav", ".mp3"]:
                content_type = ContentMultimediaFileType.objects.get(pk=ContentMultimediaFileType.AUDIO)
                self.content_multimedia_file_type = content_type
        super(ContentMultimediaFile, self).save(*args, **kwargs)


    # def __str__(self): # pragma: no cover
    #     return str(self.file_upload.path)
    def __str__(self): # pragma: no cover
        return str(self.file_name)

    def __unicode__(self):
        return self.file_upload.path

    @property
    def get_path(self):
        return f"{settings.SERVER}{self.file_upload.url}"

    @property
    def isImage(self):
        return self.content_multimedia_file_type.content_multimedia_file_type == "IMAGE"

    @property
    def isVideo(self):
        return self.content_multimedia_file_type.content_multimedia_file_type == "VIDEO"

mywebsite/views.py
from django.http import response
from django.shortcuts import render
from django.conf import Settings, settings
from django.http import HttpResponse
from wsgiref.util import FileWrapper
from django.views import View
from django.http import FileResponse
import urllib.request

from .models import *


# Create your views here.

def index(request):
    context = {
        "projects": Project.objects.filter(active=True),
        "media_url": settings.MEDIA_FOLDER
    }
    return render(request, 'homepage.html', context)


class ProjectView(View):

    http_method_names = ["get", "post"]


    def get(self, request, pk, *args, **kwargs):
        project = Project.objects.get(id=pk)
        par_list = []
        print(project.tags.all())
        for pro in project.paragraph_set.all().order_by('id_name'):
            if pro.content:
                par_list.append({
                    "body": pro.body,
                    "path": pro.content.file_upload.url,
                    "type": pro.content.content_multimedia_file_type.content_multimedia_file_type
                })
            else:
                par_list.append({
                    "body": pro.body,
                    "path": None,
                    "type": None
                })

        context = {
            "project": project,
            "paragraphs": par_list
        }
        return render(request, 'post.html', context)



class Resume(View):

    http_method_names = ["get", "post"]


    def get(self, request, *args, **kwargs):
        file = urllib.request.urlopen(settings.MEDIA_FOLDER+'files/brunogrifo.pdf')
        with file as fh:
            response = HttpResponse(fh.read(), content_type="application/pdf")
            response['Content-Disposition'] = 'inline; filename=brunogrifo.pdf'
            return response

mywebsite/templates/base.html
{% load static i18n %}
<!DOCTYPE html>
<html lang="pt">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="initial-scale=1, maximum-scale=1">
  {% block title %}<title>AboutMe</title>{% endblock %}

  <link href="{% static 'main.css' %}" rel="stylesheet">
  <meta property="og:image" content="https://about-me-bgrifo.s3.eu-west-2.amazonaws.com/media/files/preview.png" />
  <link rel="icon" href="{{media_url}}files/bgrifo.png">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.14.0/js/all.min.js" integrity="sha512-YSdqvJoZr83hj76AIVdOcvLWYMWzy6sJyIMic2aQz5kh2bPTd9dzY3NtdeEAzPp/PhgZqr4aJObB3ym/vsItMg==" crossorigin="anonymous"></script>

  {% block styles %}
  {% endblock %}
</head>

<body>
  {% block content %}
  {% endblock %}
  <script type="text/javascript" src="{% static 'main.js' %}"></script>
  {% block scripts %}
  {% endblock %}
</body>

</html>

mywebsite/templates/feed.html
{% extends 'index.html' %}
{% load static %}

{% block body %}
    
{% endblock %}

mywebsite/templates/homepage.html
{% extends 'index.html' %}
{% load static i18n %}

{% block body %}
    <div class="container">
        <div class="sub_container black_container" >
            

            <div class="title_slide">

                <p class="myname">Hi, my name is Bruno Grifo</p>

            </div>
            <div class="parent-intro">
                <div class="intro">
                    <p>I am from Coruche, world capital of cork.</p>
                    <p>I lived in Coimbra, where I met my beautifull girlfriend.</p>
                    <p>I'm currently living in <mark class="blue">Lisbon</mark>.</p>
                    <p>I've used the same hair cut for the past 10 years.</p>
                    <p>I have five dogs and I love them all.</p>
                    <p>I'm a <mark class="blue">software developer</mark> and I like <mark class="blue">web development</mark>, so yes, I <mark class="blue">code</mark> sometimes.</p>
                    <p>In college I was a member of <a href="http://www.jest.pt" target="_blank">JEST</a> which is basically a bunch of cool and smart people.</p>
                    <p>I am into cocktail mixology and wine tasting.</p>
                    <p>I love tennis and I want to believe that, one day, i'll be as good as Roger Federer.</p>
                    <p>I have a <a href="{% url 'mywebsite:Resume' %}" target="_blank">resumé</a> because it is kind of mandatory, so go ahead and click on that.</p>
                    <p>I'm just a common guy from any reasonable prespective.</p>
                    <p>I'm a hero from my mom's prespective.</p>
                </div>

                <div class="thumbnail"><img src="{{media_url}}img/semcopo.png" alt=""></div>
            </div>

            <div class="scroll"></div>

            
        </div>
        <div class="sub_container white_container" >
            <div class="title">
                <p>Main Outdoors Activities</p>

            </div>
            <div class="description">
                I strongly believe that everyone must be able to manage a good healthy work-life balance, so I always try to make sure that I do my best at work and enjoy my free time later. 
                With almost all of my free day light time filled with theese activities, it helps me to <mark class="darkblue">stay healthy</mark> and <mark class="darkblue">relieve stress</mark>. I also love to go out with friends and family which I usually do on weekends.
            </div>

            <div class="swiper-container">
                <div class="swiper-wrapper">
                <div class="swiper-slide">
                    <div class="container-general">
                    <div class="gallery-wrap wrap-effect">
                        <div class="item" style="border-top-left-radius: 20px;
                        border-bottom-left-radius: 20px;
                        background-image: url('{{media_url}}img/padel.jpeg');"></div>
                        <div class="item" style="background-image: url('{{media_url}}img/tenis.jpeg');"></div>
                        <div class="item" style="background-image: url('{{media_url}}img/swim.jpg');"></div>
                        <div class="item" style="background-image: url('{{media_url}}img/surf.jpeg');"></div>
                        <div class="item" style="background-image: url('{{media_url}}img/trail.jpeg');"></div>
                        <div class="item" style="border-top-right-radius: 20px;
                        border-bottom-right-radius: 20px;
                        background-image: url('{{media_url}}img/bycicle.jpeg');"></div>
                    </div>
                    </div>
                </div>
                </div>
            </div>
            
        </div>
        <div class="sub_container black_container" >
            <div class="title">

                <p>Hoobies</p>

            </div>
            <div class="split">
                <div>
                    <img src="{{media_url}}img/controller.png" alt="Controller">
                </div>
                <div>
                    <img class="netflix" src="{{media_url}}img/netflix.png" alt="Netflix">
                </div>
                <div>
                    <img src="{{media_url}}img/code.png" alt="Code">
                </div>
            </div>

            <div class="description">
                    When it comes to hobbies, althought I have a lot of them, like most people do, I usually go for the same three, which are <mark class="blue">video games</mark>, <mark class="blue">movies or tv series</mark> and working on my <mark class="blue">project ideias or coding</mark>. I don't like to play single player games so I only go online when my friends are on discord, and when my girlfriend is at home we usually watch some Netflix and althought is not that often, we recently started to assemble puzzles. Since I moved to Lisbon, when i'm alone and I don't feel like playing, i've been enjoying myself working on my own projects/ideias.
            </div>
        </div>

        <div class="sub_container white_container projects" >

            <div class="title">

                <p>Mini Projects</p>

            </div>
            <div class="description">
                I've always loved to do coding projects and participate on hackathons and engineering competitions during my journey in college, however, and spite of having a lot of cool ideas, i've never really dedicated myself to my own mini projects. That changed a little bit in 2021 Spring. Being locked down by the covid-19 pandemic and not feeling challenged with my job at the time, this was a way of keep learning about the things that I like. I plan on keep working on my own ideas and this section will serve as a blog for that.
            </div>
              <section class="timeline">

                {% for project in projects%}

                    <div class="timeline-item">
                
                        <div class="timeline-img"></div>
                
                        <div class="timeline-content timeline-card ">
                        <div class="timeline-img-header" style="background: linear-gradient(rgba(0, 0, 0, 0), rgba(0, 0, 0, .4)), url('{{project.image.file_upload.url}}') center center no-repeat; background-size: cover;">
                            <h2>{{project.title}}</h2>
                        </div>
                        <div class="date">{{ project.added|date:"M d, Y" }}</div>
                        <p>{{project.description}}</p>
                        <a class="bnt-more" href="{% url 'mywebsite:ProjectView' project.id %}" target="_blank">More</a>
                        </div>
                
                    </div> 

                {% endfor %}
                   
            
            </section>
            
        </div>
        
    </div>  
      
{% endblock body%}

mywebsite/templates/index.html
{% extends 'base.html' %}
{% load static i18n %}

{% block content %}
    
    {% block header %}
        {%comment%}
        {% include 'navbar.html' %}
        {% endcomment %}
    {% endblock header%}

    {% block body %}           
    {% endblock body%}
    

    {% block footer %}
    {% endblock %}

{% endblock %}

mywebsite/templates/navbar.html
{% load static %}

<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="">
        <img class="img-fluid" src="/media/img/bgrifo.png" alt="Logo" alt="10.digital logo" style="height: 66px;">
    </a>

</nav>

mywebsite/templates/post.html
{% extends 'index.html' %}
{% load static i18n %}

{% block body %}
<div class="header" style="background: {{project.color}}80;">
    <div class="header-intro">
        <img src="{{project.image.file_upload.url}}" alt="Avatar">
        <div class="top">
        <h1>{{project.title}}</h1>
        </div>
        <div class="bottom">
            {% for tag in project.tags.all%}
            <span>#{{tag.name}}</span>
            {% endfor %}
        </div>
    </div>
    <div class="header-curve">
        <svg data-name="Layer 1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1200 120" preserveAspectRatio="none">
            <path d="M321.39,56.44c58-10.79,114.16-30.13,172-41.86,82.39-16.72,168.19-17.73,250.45-.39C823.78,31,906.67,72,985.66,92.83c70.05,18.48,146.53,26.09,214.34,3V0H0V27.35A600.21,600.21,0,0,0,321.39,56.44Z" class="shape-fill"></path>
        </svg>
    </div>
    
</div>
<div class="project_container">
    {% for par in paragraphs%}
        <div class="paragraph">
            {{par.body}}
        </div>
        {% if par.type == "IMAGE" %}
            <div class="picture">
                <img src="{{par.path}}" alt="Avatar">
            </div>
        {% endif %}
    {% endfor %}
    
</div>
<br><br>
      
{% endblock body%}